### ISSUE TITLE
go.mod support?

### ISSUE THREAD

**Issue by diamondburned** [librespot-org/librespot-golang#17]
I'm forking my own to add go.mod support, but if the maintainer is still alive, please reply to this, so I could promptly make a PR.

**Comment by xplodwild** [comment]
I'm still alive, if you make a PR for this I'd be more than happy to merge it

**Comment by diamondburned** [comment]
[Does this package structure look ok?](https://github.com/diamondburned/librespot-golang/) I changed it from the old `src/` structure of Rust's.

Importing goes 
```go
import (
	"github.com/diamondburned/librespot-golang/librespot"
	"github.com/diamondburned/librespot-golang/librespot/core"
)
```

**Comment by xplodwild** [comment]
Looks good to me!

**Comment by diamondburned** [comment]
Opened a PR: https://github.com/librespot-org/librespot-golang/pull/18

**Comment by xplodwild** [comment]
Merged PR, so closing this issue
