### ISSUE TITLE
Album art doesn't seem to work

### ISSUE THREAD

**Issue by drunlade** [librespot-org/librespot-golang#24]
Trying to get the art to load when playing a track. Doesn't seem to work.

```
// spItem is a Spotify.Track
spItem, err := spSession.GetTrack(utils.Base62ToHex(libItem.ID))

if err != nil || spItem == nil {
  glog.Error("spotify track not found when getting album art: " + libItem.ID)
  return
}

spArt := spItem.GetAlbum().GetCover()

spew.Dump(spArt)

if len(spArt) == 0 {
  glog.Error("no art for spotify track: " + libItem.ID)
  return
}

firstImage := spArt[0]

spew.Dump(firstImage)
```
No matter the track I try, it always says there's no art. The `GetCover` function always returns an empty array.

**Comment by xplodwild** [comment]
If I remember correctly, Spotify deprecated most of these in favor of the Web API. The official Spotify client relies on many Web API calls now rather than the internal protocol. I'll have a look though in recent dumps.

**Comment by drunlade** [comment]
@xplodwild Oh thanks! That's good to know, I'll look into making web-api calls then.

I did fix something recently as well, looks like their internal protocol returns the rating or popularity or one of those things (not at my PC right now) as a float rather than an int, causing a runtime error. I'll make a pull request when I get a mo.

**Comment by drunlade** [comment]
Closing since this is likely covered by using the WebAPI now.

**Comment by xplodwild** [comment]
Just in case you didn't know and for futureproofing this issue, you can use `mercury.GetToken` to get WebAPI OAuth2 tokens from the current authentication.

**Comment by drunlade** [comment]
@xplodwild Neat, so I don't need to jump through any WebAPI auth hoops. I'm having a lot of fun developing stuff with this library.

**Comment by drunlade** [comment]
@xplodwild I took a look at the WebAPI docs and it seems I'd have to jump through a load of hoops (create/register a "web app" etc) that I don't really want to have to do. The LibreSpot stuff is nice because "it just works". I don't really want to register an app, link an ID, agree to various terms, etc

I think I'll just have to live with the limitations.
