### ISSUE TITLE
json error on search

### ISSUE THREAD

**Issue by irgendwr** [librespot-org/librespot-golang#26]
I now get the following error:
`json: cannot unmarshal number 69.0 into Go struct field Track.results.tracks.hits.popularity of type int`
when searching via:
`s.session.Mercury().Search(query, limit, session.Country(), session.Username())`

**Comment by xplodwild** [comment]
Seems like they changed the type of the popularity value. You can simply change the field "popularity" from int to float64, I'll make a commit later

**Comment by irgendwr** [comment]
#25 would also close this

**Comment by xplodwild** [comment]
Well done, merged
