### ISSUE TITLE
Can't install via `go get` on Windows

### ISSUE THREAD

**Issue by jscholes** [librespot-org/librespot-golang#3]
>go get -v github.com/librespot-org/librespot-golang
    github.com/librespot-org/librespot-golang (download)
    package github.com/librespot-org/librespot-golang: no Go files in %GOPATH%\src\github.com\librespot-org\librespot-golang

Any suggestions?  Running go version 1.10.2 windows/386, Windows 7.

**Comment by xplodwild** [comment]
The library uses the vendoring system, through an "src" directory. You should either use godep to include it, or clone the repository directly.
