### ISSUE TITLE
How to get image url from file_id ?

### ISSUE THREAD

**Issue by vikbez** [librespot-org/librespot-golang#4]
I'm trying to get a track's artwork using:

`track.GetAlbum().GetCoverGroup().GetImage()[0].GetFileId()`

Do you know what to do next with the file_id ?

Thanks

**Comment by vikbez** [comment]
this works:

```
func fileid2image(file_id []byte) string {
	return fmt.Sprintf("https://i.scdn.co/image/%032s", hex.EncodeToString(file_id))
}```

**Comment by chfanghr** [comment]
Helpful.Thank you.
