### ISSUE TITLE
Deadlock after latest commit

### ISSUE THREAD

**Issue by ViRb3** [librespot-org/librespot-golang#8]
After applying https://github.com/librespot-org/librespot-golang/commit/23bdf13d9bf3771324c5a772853b3e0494e977cf, I get a consistent deadlock.

Execution reaches [line 66](https://github.com/librespot-org/librespot-golang/commit/23bdf13d9bf3771324c5a772853b3e0494e977cf#diff-a6f006b5084c7da953c42a3646d056aaR66) and sends a packet to get the key. Immediately after that it locks `seqChanLock` and blocks on receiving the key. A moment later, `HandleCmd` is called with the key. However, before updating the key, the method locks on the already locked `seqChanLock` at [line 99](https://github.com/librespot-org/librespot-golang/commit/23bdf13d9bf3771324c5a772853b3e0494e977cf#diff-a6f006b5084c7da953c42a3646d056aaR99), resulting in a deadlock. I have a local mirror with some personal changes, so it may be my fault, but please explain exactly what race condition this prevents.

Thanks!

**Comment by benpye** [comment]
If I'm not mistaken we should be locking on line 67 and not line 66, line 66 is a read, why would we lock?

**Comment by benpye** [comment]
Evidentally I'm wrong, maybe https://godoc.org/sync#Map is what we want instead

**Comment by xplodwild** [comment]
PR has been merged, closing this issue
